# Generated by Django 4.2.4 on 2024-02-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.petphoto'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.petphoto'),
        ),
    ]
